image: "ekidd/rust-musl-builder:latest"

stages:
  - test
  - build_native
  - build_cross

test:
  stage: test
  image: "rust:latest"
  before_script:
    - apt-get update
    - apt-get install -yq capnproto
  script:
    - rustc --version
    - cargo --version
    - RUST_BACKTRACE=1 cargo test --all --verbose

audit:
  stage: test
  image: "rust:latest"
  allow_failure: true
  before_script:
    - cargo install --force cargo-audit
    - cargo generate-lockfile
  script:
    - rustc --version
    - cargo --version
    - cargo audit

clippy:
  stage: test
  image: "rust:latest"
  allow_failure: true
  before_script:
    - apt-get update
    - apt-get install -yq capnproto
    - rustup component add clippy
  script:
    - rustc --version
    - cargo --version
    - cargo clippy --all-targets --all-features -- -D warnings

linux-native:
  stage: build_native
  image: "rust:latest"
  before_script:
    - apt-get update
    - apt-get install -yq capnproto
  script:
    - rustc --version
    - cargo --version
    - cargo build --release
  artifacts:
    paths:
      - target/release/flow-cli

linux-native-ffi-example:
  stage: build_native
  image: "rust:latest"
  before_script:
    - apt-get update
    - apt-get install -yq capnproto
  script:
    - rustc --version
    - cargo --version
    - cargo build --release
    - cd flow-ffi/bindings/c/
    - gcc -g example.c -o example -Wl,-rpath,../../../target/release -lmemflow -L./../../../target/release

linux-musl:
  stage: build_cross
  before_script:
    - sudo apt-get update
    - rustup update
    - sudo apt-get install -yq capnproto
  script:
    - rustc --version
    - cargo --version
    - cargo build --release --target x86_64-unknown-linux-musl
  artifacts:
    paths:
      - target/x86_64-unknown-linux-musl/release/flow-cli

linux-gnu-armv6:
  stage: build_cross
  before_script:
    - sudo apt-get update
    - rustup update
    - sudo apt-get install -yq capnproto
    - sudo apt-get install -yq gcc-arm-linux-gnueabi
    - rustup target add arm-unknown-linux-gnueabi
    - sudo chmod 777 /home/rust/.cargo/config
    - echo "[target.arm-unknown-linux-gnueabi]" >> ~/.cargo/config
    - echo "linker = \"/usr/bin/arm-linux-gnueabi-gcc\"" >> ~/.cargo/config
    - echo "ar = \"/usr/arm-linux-gnueabi/bin/ar\"" >> ~/.cargo/config
  script:
    - rustc --version
    - cargo --version
    - cargo build --release --target arm-unknown-linux-gnueabi
  artifacts:
    paths:
      - target/arm-unknown-linux-gnueabi/release/flow-cli

linux-gnu-armv6hf:
  stage: build_cross
  before_script:
    - sudo apt-get update
    - rustup update
    - sudo apt-get install -yq capnproto
    - sudo apt-get install -yq gcc-arm-linux-gnueabihf
    - rustup target add arm-unknown-linux-gnueabihf
    - sudo chmod 777 /home/rust/.cargo/config
    - echo "[target.arm-unknown-linux-gnueabihf]" >> ~/.cargo/config
    - echo "linker = \"/usr/bin/arm-linux-gnueabihf-gcc\"" >> ~/.cargo/config
    - echo "ar = \"/usr/arm-linux-gnueabihf/bin/ar\"" >> ~/.cargo/config
  script:
    - rustc --version
    - cargo --version
    - cargo build --release --target arm-unknown-linux-gnueabihf
  artifacts:
    paths:
      - target/arm-unknown-linux-gnueabihf/release/flow-cli

linux-gnu-armv7hf:
  stage: build_cross
  before_script:
    - sudo apt-get update
    - rustup update
    - sudo apt-get install -yq capnproto
    - sudo apt-get install -yq gcc-arm-linux-gnueabihf
    - rustup target add armv7-unknown-linux-gnueabihf
    - sudo chmod 777 /home/rust/.cargo/config
    - echo "[target.armv7-unknown-linux-gnueabihf]" >> ~/.cargo/config
    - echo "linker = \"/usr/bin/arm-linux-gnueabihf-gcc\"" >> ~/.cargo/config
    - echo "ar = \"/usr/arm-linux-gnueabihf/bin/ar\"" >> ~/.cargo/config
  script:
    - rustc --version
    - cargo --version
    - cargo build --release --target armv7-unknown-linux-gnueabihf
  artifacts:
    paths:
      - target/armv7-unknown-linux-gnueabihf/release/flow-cli

windows-mingw-x64:
  stage: build_cross
  before_script:
    - sudo apt-get update
    - rustup update
    - sudo apt-get install -yq capnproto
    - sudo apt-get install -yq gcc-mingw-w64
    - rustup target add x86_64-pc-windows-gnu
    - sudo chmod 777 /home/rust/.cargo/config
    - echo "[target.x86_64-pc-windows-gnu]" >> ~/.cargo/config
    - echo "linker = \"/usr/bin/x86_64-w64-mingw32-gcc\"" >> ~/.cargo/config
    - echo "ar = \"/usr/x86_64-w64-mingw32/bin/ar\"" >> ~/.cargo/config
  script:
    - rustc --version
    - cargo --version
    - cargo build --release --target x86_64-pc-windows-gnu
  artifacts:
    paths:
      - target/x86_64-pc-windows-gnu/release/flow-cli.exe
