[package]
name = "flow-derive"
version = "0.1.0"
authors = ["ko1N <ko1N1337@gmail.com>"]
edition = "2018"

[lib]
test = false
bench = false
proc-macro = true

[dependencies]
quote = "1.0"
syn = { version = "1.0", features = ["visit"] }

