[package]
name = "flow-qemu-bridge"
version = "0.1.0"
authors = ["ko1N <ko1N1337@gmail.com>"]
edition = "2018"

[lib]
name = "flow_qemu_bridge"
crate-type = ["cdylib"]

[features]
default = ["locking"]
locking = []

[build-dependencies]
capnpc = "0.10.1"

[dependencies]
ctor = "*"
libc-print = "*"
libc = "*"
lazy_static = "1.4.0"
rand = "0.7.0"
tokio = "0.1.22"
capnp = "0.10.3"
capnp-rpc = "0.10.0"
address = { path = "../../flow-core/address" }
arch = { path = "../../flow-core/arch" }
mem = { path = "../../flow-core/mem" }
flow-va = { path = "../../flow-va" }
pretty_env_logger = "0.*"
url = "2.1.0"
