[package]
name = "flow-win32"
version = "0.1.0"
authors = ["ko1N <ko1N1337@gmail.com>"]
edition = "2018"

[dependencies]
address = { path = "../flow-core/address" }
arch = { path = "../flow-core/arch" }
mem = { path = "../flow-core/mem" }
log = { version = "0.*", default-features = false }
byteorder = "1.*"
num = "0.*"
goblin = { git = "https://github.com/ko1N/goblin" }
scroll = "0.9"
pretty-hex = "0.*"
clap = "2.*"
uuid = "0.*" # remove this if goblin has this built in
duma = "*"
dirs = "2.*"
pdb = { git = "https://github.com/willglynn/pdb" }
