[package]
name = "flow-core"
version = "0.1.0"
authors = ["ko1N <ko1N1337@gmail.com>"]
edition = "2018"

[dependencies]
address = { path = "address" }
arch = { path = "arch" }
mem = { path = "mem" }

# integrate win32, linux, qemu, etc in core if applicable
# integrate va in core as a subcrate?
flow-win32 = { path = "../flow-win32" }
