[package]
name = "flow-core"
version = "0.1.0"
authors = ["ko1N <ko1N1337@gmail.com>"]
edition = "2018"

[dependencies]
dataview = "0.1"
byteorder = "1.3.2"
log = { version = "0.4.8", default-features = false }
regex = "1.3.1"
#unicorn = { version = "0.9.1", optional = true }

[features]
default = []
bridge = [] # enables the connector bridge (requires tokio)
#emulator = ["unicorn"] # enables the process emulator (requires unicorn engine)
