[package]
name = "vat"
version = "0.1.0"
authors = ["ko1N <ko1N1337@gmail.com>"]
edition = "2018"

[features]
default = ["x64", "x64-pae", "x86"]
x64 = []
x64-pae = []
x86 = []

[dependencies]
address = { path = "../address" }
arch = { path = "../arch" }
mem = { path = "../mem" }
log = { version = "0.4.8", default-features = false }
byteorder = "1.3.2"
